server:
  port: 8080
  error:
    path: /error/
  servlet:
    context-path: /test

spring:
  profiles:
    active: local
  application:
    name: spring316
  graphql:
    cors:
      allowed-headers: "*"
      allowed-methods: "*"
      allow-credentials: true
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: classpath:/templates/
      suffix: .html
  servlet:
    multipart:
      enabled: false
      max-file-size: 100MB
      max-request-size: 500MB
      location: c:\\dev
  thymeleaf:
    enabled: true
    check-template-location: true
    cache: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.spring316.dto
  mapper-locations: mappers/**/*.xml

logging:
  level:
    com.spring316: info
    org.hibernate.type.descriptor.sql: info
    org.springframework.security: info